# Build Stage:
FROM golang:1.18.3 as builder

## Install build dependencies.
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

## Add Source Code
ADD . /open-simulator
WORKDIR /open-simulator

## Build Step
RUN go mod tidy
RUN go build cmd/main.go

# Package Stage
FROM debian:bookworm-slim
COPY --from=builder /open-simulator/main /
